services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: shumen_traffic_mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - shumen_traffic_network
    volumes:
      - mssql-data:/var/opt/mssql

  webapi:
    image: ghcr.io/lneshev/shumen-traffic-webapi:latest
    pull_policy: always
    container_name: shumen_traffic_webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__App=${WebApi__ConnectionStrings__App}
      - ConnectionStrings__Log=${WebApi__ConnectionStrings__Log}
      - ConsumersConfiguration__WebApp__ApplicationUrl=${WebApi__ConsumersConfiguration__WebApp__ApplicationUrl}
      - UsersConfiguration__SuperAdmin__Email=${WebApi__UsersConfiguration__SuperAdmin__Email}
      - UsersConfiguration__SuperAdmin__Password=${WebApi_UsersConfiguration__SuperAdmin__Password}
    ports:
      - "5000:80"
      - "5001:8081"
    networks:
      - shumen_traffic_network
    depends_on:
      - mssql

  webapp:
    image: ghcr.io/lneshev/shumen-traffic-webapp:latest
    pull_policy: always
    container_name: shumen_traffic_webapp
    environment:
      - NEXT_PUBLIC_WEB_API_BASE_URL=${WebApp__NEXT_PUBLIC_WEB_API_BASE_URL}
    ports:
      - "3000:3000"
    networks:
      - shumen_traffic_network
    depends_on:
      - webapi

networks:
  shumen_traffic_network:
    driver: bridge

volumes:
  mssql-data: