<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElmahCore" Version="2.1.2" />
    <PackageReference Include="ElmahCore.Sql" Version="2.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MoravianStar.WebAPI" Version="1.43.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShumenTraffic.Common.Services\ShumenTraffic.Common.Services.csproj" />
    <ProjectReference Include="..\ShumenTraffic.Common.DataAccess\ShumenTraffic.Common.DataAccess.csproj" />
    <ProjectReference Include="..\ShumenTraffic.Web.Services\ShumenTraffic.Web.Services.csproj" />
  </ItemGroup>

</Project>
