//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumenTraffic.Common.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShumenTraffic.Common.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All schedule courses in schedule with ID: &apos;{0}&apos; must have routes that are for the schedule&apos;s bus line and direction..
        /// </summary>
        public static string AllScheduleCoursesInScheduleMustHaveRoutesThatAreForSchedulesBusLineAndDirection {
            get {
                return ResourceManager.GetString("AllScheduleCoursesInScheduleMustHaveRoutesThatAreForSchedulesBusLineAndDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bus line with line number: &apos;{0}&apos; already exists..
        /// </summary>
        public static string BusLineWithLineNumberAlreadyExists {
            get {
                return ResourceManager.GetString("BusLineWithLineNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bus stop with name: &apos;{0}&apos; already exists..
        /// </summary>
        public static string BusStopWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("BusStopWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DayType_Saturday {
            get {
                return ResourceManager.GetString("DayType_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DayType_Sunday {
            get {
                return ResourceManager.GetString("DayType_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string DayType_Weekday {
            get {
                return ResourceManager.GetString("DayType_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more databases could not be updated. Main status: {0}..
        /// </summary>
        public static string OneOrMoreDatabasesCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("OneOrMoreDatabasesCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more schedules for bus line: &apos;{0}&apos;, direction: &apos;{1}&apos; and day type: &apos;{2}&apos; already exist for this date range. Either try saving this schedule with different parameters or modify/delete some of the existing schedules first. Problematic schedule IDs: {3}..
        /// </summary>
        public static string OneOrMoreSchedulesForBusLineExist {
            get {
                return ResourceManager.GetString("OneOrMoreSchedulesForBusLineExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be of type: &apos;{1}&apos; in order to apply attribute: &apos;{2}&apos;..
        /// </summary>
        public static string PropertyMustBeOfTypeInOrderToApplyAttribute {
            get {
                return ResourceManager.GetString("PropertyMustBeOfTypeInOrderToApplyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RouteDirection_One {
            get {
                return ResourceManager.GetString("RouteDirection_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RouteDirection_Two {
            get {
                return ResourceManager.GetString("RouteDirection_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route stop must either have a location or a bus stop..
        /// </summary>
        public static string RouteStopMustEitherHaveALocationOrABusStop {
            get {
                return ResourceManager.GetString("RouteStopMustEitherHaveALocationOrABusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A route with name: &apos;{0}&apos;, bus line: &apos;{1}&apos; and direction: &apos;{2}&apos; already exists..
        /// </summary>
        public static string RouteWithNameBusLineAndDirectionAlreadyExists {
            get {
                return ResourceManager.GetString("RouteWithNameBusLineAndDirectionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data to a database without a transaction is not allowed. First open a database transaction and then save&amp;commit the changes..
        /// </summary>
        public static string SavingDataToDBWithoutATransactionIsNotAllowed {
            get {
                return ResourceManager.GetString("SavingDataToDBWithoutATransactionIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string SchedulePriority_High {
            get {
                return ResourceManager.GetString("SchedulePriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SchedulePriority_Normal {
            get {
                return ResourceManager.GetString("SchedulePriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be less than or equal to end date..
        /// </summary>
        public static string StartDateMustBeLessThanOrEqualToEndDate {
            get {
                return ResourceManager.GetString("StartDateMustBeLessThanOrEqualToEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numeric part in parameter {0} should be no more than {1} digits..
        /// </summary>
        public static string TheNumericPartInParameterShouldBeNoMoreThanXDigits {
            get {
                return ResourceManager.GetString("TheNumericPartInParameterShouldBeNoMoreThanXDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route cannot be saved, because the estimated minutes from start for the stops are not correct. The estimated minutes from start should be in ascending order..
        /// </summary>
        public static string TheRouteCannotBeSavedBecauseTheEstimatedMinutesFromStartAreNotCorrect {
            get {
                return ResourceManager.GetString("TheRouteCannotBeSavedBecauseTheEstimatedMinutesFromStartAreNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route cannot be saved, because the stop order is not correct. The stop order should be unique for each stop..
        /// </summary>
        public static string TheRouteCannotBeSavedBecauseTheStopOrderIsNotCorrect {
            get {
                return ResourceManager.GetString("TheRouteCannotBeSavedBecauseTheStopOrderIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route should end with a bus stop..
        /// </summary>
        public static string TheRouteShouldEndWithABusStop {
            get {
                return ResourceManager.GetString("TheRouteShouldEndWithABusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route should start with a bus stop..
        /// </summary>
        public static string TheRouteShouldStartWithABusStop {
            get {
                return ResourceManager.GetString("TheRouteShouldStartWithABusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transportation company with name: &apos;{0}&apos; already exists..
        /// </summary>
        public static string TransportationCompanyWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("TransportationCompanyWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or unsupported enum value of enum type: &apos;{0}&apos;..
        /// </summary>
        public static string UnknownOrUnsupportedEnumValueOfEnumType {
            get {
                return ResourceManager.GetString("UnknownOrUnsupportedEnumValueOfEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (Longitude) must be in range {0} to {1}..
        /// </summary>
        public static string XLongitudeMustBeInRange {
            get {
                return ResourceManager.GetString("XLongitudeMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y (Latitude) must be in range {0} to {1}..
        /// </summary>
        public static string YLatitudeMustBeInRange {
            get {
                return ResourceManager.GetString("YLatitudeMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete bus line: &apos;{0}&apos;, because it has routes..
        /// </summary>
        public static string YouAreNotAllowedToDeleteBusLineBecauseItHasRoutes {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteBusLineBecauseItHasRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete bus line: &apos;{0}&apos;, because it has schedules..
        /// </summary>
        public static string YouAreNotAllowedToDeleteBusLineBecauseItHasSchedules {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteBusLineBecauseItHasSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete bus stop: &apos;{0}&apos;, because it is used in one or more routes..
        /// </summary>
        public static string YouAreNotAllowedToDeleteBusStop {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteBusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete route: &apos;{0}&apos;, because it is used in one or more schedule courses..
        /// </summary>
        public static string YouAreNotAllowedToDeleteRoute {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete transportation company: &apos;{0}&apos;, because it has bus lines..
        /// </summary>
        public static string YouAreNotAllowedToDeleteTransportationCompany {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteTransportationCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete zone: &apos;{0}&apos;, because it has bus stops..
        /// </summary>
        public static string YouAreNotAllowedToDeleteZone {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A zone with name: &apos;{0}&apos; already exists..
        /// </summary>
        public static string ZoneWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("ZoneWithNameAlreadyExists", resourceCulture);
            }
        }
    }
}
